name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Format
      working-directory: dnevest
      run: cargo fmt --check

    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      working-directory: dnevest
      run: cargo build --verbose

